### ISSUE TITLE
Flashing in dark mode

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/blog-next#25]
If I choose dark-mode and then I redirect to another page, the page loads light mode first and the script changes to dark after that resulting in flashing.
Let's wait it out, what the big dogs will do.

**Comment by balintkiraly** [comment]
That's caused by the SSR. The server send back the HTML but it doesn't know about which theme was set by the user, because it only stored in the local storage. So default it start rendering the light one. We had a similar issue with the tanulo project but with Tailwind and NextJS.
BTW there is something in the documentation that can be useful https://chakra-ui.com/docs/features/color-mode#for-gatsby 
I'm not sure this solve the flashing or not.

**Comment by triszt4n** [comment]
Will be solved by using Gatsby's Link components, rather than Chakra's Link components in PR #26
